variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "public_subnet1_name" {}
variable "public_subnet1_cidr" {}
variable "IGW_name" {}
variable "Main_Routing_Table" {}
variable "key_name" {}